# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        Document,
        DocumentDeleteResponse,
        DocumentStatus,
        Project,
        ProjectDeleteResponse,
        RetrievalContent,
        RetrievalMetadata,
        RetrievalMetadataType,
        RetrievalStrategy,
        SearchResponse,
        UploadResponse,
    )
    from . import projects, upload
    from .client import Asynctropicalia, tropicalia
    from .environment import tropicaliaEnvironment
    from .version import __version__
_dynamic_imports: typing.Dict[str, str] = {
    "Asynctropicalia": ".client",
    "Document": ".types",
    "DocumentDeleteResponse": ".types",
    "DocumentStatus": ".types",
    "Project": ".types",
    "ProjectDeleteResponse": ".types",
    "RetrievalContent": ".types",
    "RetrievalMetadata": ".types",
    "RetrievalMetadataType": ".types",
    "RetrievalStrategy": ".types",
    "SearchResponse": ".types",
    "UploadResponse": ".types",
    "__version__": ".version",
    "projects": ".projects",
    "tropicalia": ".client",
    "tropicaliaEnvironment": ".environment",
    "upload": ".upload",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Asynctropicalia",
    "Document",
    "DocumentDeleteResponse",
    "DocumentStatus",
    "Project",
    "ProjectDeleteResponse",
    "RetrievalContent",
    "RetrievalMetadata",
    "RetrievalMetadataType",
    "RetrievalStrategy",
    "SearchResponse",
    "UploadResponse",
    "__version__",
    "projects",
    "tropicalia",
    "tropicaliaEnvironment",
    "upload",
]
