# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .document import Document
    from .document_delete_response import DocumentDeleteResponse
    from .document_status import DocumentStatus
    from .project import Project
    from .project_delete_response import ProjectDeleteResponse
    from .retrieval_content import RetrievalContent
    from .retrieval_metadata import RetrievalMetadata
    from .retrieval_metadata_type import RetrievalMetadataType
    from .retrieval_strategy import RetrievalStrategy
    from .search_response import SearchResponse
    from .upload_response import UploadResponse
_dynamic_imports: typing.Dict[str, str] = {
    "Document": ".document",
    "DocumentDeleteResponse": ".document_delete_response",
    "DocumentStatus": ".document_status",
    "Project": ".project",
    "ProjectDeleteResponse": ".project_delete_response",
    "RetrievalContent": ".retrieval_content",
    "RetrievalMetadata": ".retrieval_metadata",
    "RetrievalMetadataType": ".retrieval_metadata_type",
    "RetrievalStrategy": ".retrieval_strategy",
    "SearchResponse": ".search_response",
    "UploadResponse": ".upload_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Document",
    "DocumentDeleteResponse",
    "DocumentStatus",
    "Project",
    "ProjectDeleteResponse",
    "RetrievalContent",
    "RetrievalMetadata",
    "RetrievalMetadataType",
    "RetrievalStrategy",
    "SearchResponse",
    "UploadResponse",
]
