# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .retrieval_content import RetrievalContent


class SearchResponse(UniversalBaseModel):
    completion: typing.Optional[str] = pydantic.Field(default=None)
    """
    AI-generated answer (when generate_answer is true)
    """

    retrieval_contents: typing.List[RetrievalContent]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
